[package]
name = "niz-core"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true }
serde_json = { workspace = true }
tiny-keccak = { workspace = true }
uuid = { workspace = true }
