[package]
name = "niz-proc-macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
syn = { version = "1.0.84", features = ["full"] }
quote = { version = "1.0" }
